services:
  # Backend Service
  - type: web
    name: horizon-bank-api
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/horizon-bank
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://horizon-bank-frontend.onrender.com
      - key: ADMIN_PASSWORD
        value: admin123

  # Frontend Service
  - type: web
    name: horizon-bank-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        value: https://horizon-bank-api.onrender.com
