services:
  # Backend Service
  - type: web
    name: horizon-bank-api
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://biggerthanlife1998:P4ODUJkCIsAFLJVg@nfc.gwsvvhn.mongodb.net/?retryWrites=true&w=majority&appName=nfc
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://horizon-bank-frontend-docker.onrender.com
      - key: ADMIN_PASSWORD
        value: admin123

  # Frontend Service (Docker)
  - type: web
    name: horizon-bank-frontend-docker
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    dockerBuildArgs:
      - key: VITE_API_URL
        value: https://horizon-bank-api.onrender.com
    envVars:
      - key: VITE_API_URL
        value: https://horizon-bank-api.onrender.com
    plan: free
